### ISSUE TITLE
Spring boot Application hangs and does not start with Azure Key Vault Starter dependency  when asked to bring all keys from key vault

### ISSUE THREAD

**Issue by suhas9844** [microsoft/azure-spring-boot#909]
## Environment
- Spring boot starter:
  
  - key vault spring boot starter
 
  
- OS Type: MacOS
- Java version: 
  
  - 1.9
  

## Summary

Spring boot Application hangs and does not start with Key Vault Starter.
## Reproduce steps

Use this version of key valut starter
```
<dependency>
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
<version>2.3.1</version>
 <scope>runtime</scope>
</dependency>
```

use this below configuration in application.properties and try to start the project
azure.keyvault.enabled=true
azure.keyvault.uri=#####
azure.keyvault.client-id=#######
azure.keyvault.tenant-id=#######
azure.keyvault.client-key=#######
azure.keyvault.token-acquire-timeout-seconds=60

## Expected Results

Spring should have loaded the keys from the key vault.

**Comment by suhas9844** [comment]
The above issue is solved with adding the below property 
azure.keyvault.secret.keys=iothubconn

But now it gives a new error:
2020-06-03 17:02:00.0956|ERROR||reactor.util.Loggers$Slf4JLogger:319|[id: 0x50f5772e, L:/10.0.0.25:61508 - R:m3cg-key-vault.vault.azure.net/13.66.230.241:443] Error was received while reading the incoming data. The connection will be closed.
java.lang.NoSuchMethodError: 'java.lang.String com.azure.core.util.CoreUtils.bomAwareToString(byte[], java.lang.String)'
	at com.azure.core.http.netty.NettyAsyncHttpClient$ReactorNettyHttpResponse.lambda$getBodyAsString$4(NettyAsyncHttpClient.java:215)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:366)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:423)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:607)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-06-03 17:02:00.0962|WARN||io.netty.channel.AbstractChannelHandlerContext:311|An exception 'java.lang.NoSuchMethodError: 'java.lang.String com.azure.core.util.CoreUtils.bomAwareToString(byte[], java.lang.String)'' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: 'java.lang.String com.azure.core.util.CoreUtils.bomAwareToString(byte[], java.lang.String)'
	at com.azure.core.http.netty.NettyAsyncHttpClient$ReactorNettyHttpResponse.lambda$getBodyAsString$4(NettyAsyncHttpClient.java:215)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:96)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:366)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:423)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:607)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by suhas9844** [comment]
dependency tree:

[INFO] com.m3cg.us:M3CGIoTWebAPi:jar:0.0.1-SNAPSHOT
[INFO] +- com.opencsv:opencsv:jar:5.2:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.10:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.8:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- com.azure:azure-cosmos:jar:4.0.1-beta.2:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.49.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.49.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.49.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.49.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.49.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.49.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.49.Final:compile
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.49.Final:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.0:compile
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.49.Final:compile
[INFO] |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.49.Final:compile
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.49.Final:compile
[INFO] |  |  \- io.netty:netty-codec-socks:jar:4.1.49.Final:compile
[INFO] |  +- io.projectreactor:reactor-core:jar:3.3.5.RELEASE:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  +- com.azure:azure-core:jar:1.4.0:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.11.0:compile
[INFO] |  |     +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.11.0:compile
[INFO] |  |     +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  |     \- com.fasterxml.woodstox:woodstox-core:jar:6.2.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.11.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.1.7:compile
[INFO] |  +- io.micrometer:micrometer-core:jar:1.5.1:compile
[INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] |  \- io.projectreactor.netty:reactor-netty:jar:0.9.7.RELEASE:compile
[INFO] +- com.microsoft.azure.sdk.iot:iot-service-client:jar:1.22.0:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile
[INFO] |  +- com.microsoft.azure.sdk.iot:iot-deps:jar:0.9.4:compile
[INFO] |  |  +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.3:compile
[INFO] |  |  +- org.bouncycastle:bcmail-jdk15on:jar:1.64:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO] |  |  \- org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.2.2:compile
[INFO] |  +- org.glassfish:javax.json:jar:1.0.4:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.14:compile
[INFO] |  \- org.apache.qpid:proton-j:jar:0.30.0:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] +- com.azure:azure-storage-blob:jar:12.6.1:compile
[INFO] |  \- com.azure:azure-storage-common:jar:12.6.1:compile
[INFO] |     \- com.azure:azure-core-http-netty:jar:1.5.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.3.0.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.0:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.3.0.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.35:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.35:compile
[INFO] |  +- org.springframework:spring-web:jar:5.2.6.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.2.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.2.6.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.2.6.RELEASE:compile
[INFO] |     +- org.springframework:spring-context:jar:5.2.6.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.2.6.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.3.0.RELEASE:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.2:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.2:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.springframework:spring-core:jar:5.2.6.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.2.6.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.26:compile
[INFO] +- org.springframework.boot:spring-boot-starter-validation:jar:2.3.0.RELEASE:compile
[INFO] |  +- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  \- org.hibernate.validator:hibernate-validator:jar:6.1.5.Final:compile
[INFO] |     +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |     +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] +- com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:jar:2.3.0:runtime
[INFO] |  +- com.microsoft.azure:azure-spring-boot:jar:2.3.0:runtime
[INFO] |  |  +- com.azure:azure-security-keyvault-secrets:jar:4.1.1:runtime
[INFO] |  |  \- com.azure:azure-identity:jar:1.0.4:runtime
[INFO] |  |     +- com.microsoft.azure:msal4j:jar:0.5.0-preview:runtime
[INFO] |  |     |  \- org.projectlombok:lombok:jar:1.18.12:runtime
[INFO] |  |     +- com.nimbusds:oauth2-oidc-sdk:jar:7.1.1:runtime
[INFO] |  |     |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:runtime
[INFO] |  |     |  +- com.nimbusds:content-type:jar:2.0:runtime
[INFO] |  |     |  +- com.nimbusds:lang-tag:jar:1.4.4:runtime
[INFO] |  |     |  +- com.nimbusds:nimbus-jose-jwt:jar:8.8:runtime
[INFO] |  |     |  \- com.sun.mail:javax.mail:jar:1.6.1:runtime
[INFO] |  |     |     \- javax.activation:activation:jar:1.1:runtime
[INFO] |  |     +- org.nanohttpd:nanohttpd:jar:2.3.1:runtime
[INFO] |  |     \- net.java.dev.jna:jna-platform:jar:5.4.0:runtime
[INFO] |  |        \- net.java.dev.jna:jna:jar:5.4.0:runtime
[INFO] |  +- com.microsoft.azure:azure-client-authentication:jar:1.6.13:runtime
[INFO] |  |  +- com.microsoft.azure:azure-client-runtime:jar:1.6.13:runtime
[INFO] |  |  |  \- com.microsoft.rest:client-runtime:jar:1.6.13:runtime
[INFO] |  |  |     +- com.google.guava:guava:jar:20.0:runtime
[INFO] |  |  |     +- com.squareup.retrofit2:retrofit:jar:2.5.0:runtime
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp:jar:3.14.8:runtime
[INFO] |  |  |     |  \- com.squareup.okio:okio:jar:1.17.2:runtime
[INFO] |  |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.14.8:runtime
[INFO] |  |  |     +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.14.8:runtime
[INFO] |  |  |     +- com.squareup.retrofit2:converter-jackson:jar:2.5.0:runtime
[INFO] |  |  |     +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.11.0:runtime
[INFO] |  |  |     |  \- joda-time:joda-time:jar:2.9.9:runtime
[INFO] |  |  |     +- io.reactivex:rxjava:jar:1.3.8:runtime
[INFO] |  |  |     \- com.squareup.retrofit2:adapter-rxjava:jar:2.4.0:runtime
[INFO] |  |  +- com.microsoft.azure:adal4j:jar:1.6.4:runtime
[INFO] |  |  \- com.microsoft.azure:azure-annotations:jar:1.7.0:runtime
[INFO] |  \- commons-io:commons-io:jar:2.3:runtime
[INFO] \- org.springframework.boot:spring-boot-starter-test:jar:2.3.0.RELEASE:test
[INFO]    +- org.springframework.boot:spring-boot-test:jar:2.3.0.RELEASE:test
[INFO]    +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.3.0.RELEASE:test
[INFO]    +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO]    |  \- net.minidev:json-smart:jar:2.3:runtime
[INFO]    |     \- net.minidev:accessors-smart:jar:1.2:runtime
[INFO]    |        \- org.ow2.asm:asm:jar:5.0.4:runtime
[INFO]    +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO]    |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO]    +- org.assertj:assertj-core:jar:3.16.1:test
[INFO]    +- org.hamcrest:hamcrest:jar:2.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter:jar:5.6.2:test
[INFO]    |  +- org.junit.jupiter:junit-jupiter-api:jar:5.6.2:test
[INFO]    |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO]    |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO]    |  |  \- org.junit.platform:junit-platform-commons:jar:1.6.2:test
[INFO]    |  +- org.junit.jupiter:junit-jupiter-params:jar:5.6.2:test
[INFO]    |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.6.2:test
[INFO]    |     \- org.junit.platform:junit-platform-engine:jar:1.6.2:test
[INFO]    +- org.mockito:mockito-core:jar:3.3.3:test
[INFO]    |  +- net.bytebuddy:byte-buddy:jar:1.10.10:test
[INFO]    |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.10:test
[INFO]    |  \- org.objenesis:objenesis:jar:2.6:test
[INFO]    +- org.mockito:mockito-junit-jupiter:jar:3.3.3:test
[INFO]    +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO]    |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO]    +- org.springframework:spring-test:jar:5.2.6.RELEASE:test
[INFO]    \- org.xmlunit:xmlunit-core:jar:2.7.0:test

My dependency in pom.xml:
`<dependencies>
		<dependency>
		    <groupId>com.opencsv</groupId>
		    <artifactId>opencsv</artifactId>
		    <version>5.2</version>
		</dependency>
		<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>4.0.1-beta.2</version>
        </dependency>
        <dependency>
		    <groupId>com.microsoft.azure.sdk.iot</groupId>
		    <artifactId>iot-service-client</artifactId>
		    <version>1.22.0</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.httpcomponents</groupId>
		    <artifactId>httpclient</artifactId>
		    <version>4.5.12</version>
		</dependency>
		<dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-storage-blob</artifactId>
		    <version>12.6.1</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
		    <version>2.3.0</version>
		    <scope>runtime</scope>
		</dependency>
		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>`

**Comment by suhas9844** [comment]
Update after adding azure core where the above method is present the No such method error is solved, azure cosmos sdk brings 1.4.0 version of azure core Jar.

```
<dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-core</artifactId>
		    <version>1.5.0</version>
</dependency>
```

**Comment by chenrujun** [comment]
I reported the issue [here](https://github.com/Azure/azure-sdk-for-java/issues/11808)

**Comment by vchernogorov** [comment]
The issue is still presented in `azure-keyvault-secrets-spring-boot-starter-2.3.2`.

**Comment by saragluna** [comment]
@vchernogorov we plan to perform a release in this week, please stay tuned.
